from abc import ABC, abstractmethod

class NodeHandler(ABC):

    @abstractmethod
    def accepts(self, node) -> bool: ...

    @abstractmethod
    def is_leaf(self, node) -> bool: ...

    def resolve_leaf(self, node, *, context, getter): ...

    def iter_children(self, node): ...

    def rebuild(self, node, children): ...
